services:
  - type: web
    name: fastapi-app
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT
